import { ArrowRight, CalendarDays, Check, ChevronRight, ClipboardCheck, CreditCard, Megaphone, Plus, UserPlus, Users, WalletCards } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { motion } from 'motion/react';
import { Link } from 'react-router';
import { Avatar, Badge, Button, Card } from '../../components/edunest/ui';
import { chartData } from '../../app/data';

const stats=[{label:'Total students',value:'1,248',change:'+36 this term',icon:Users,tone:'violet'},{label:'Teaching staff',value:'72',change:'96% attendance',icon:UserPlus,tone:'blue'},{label:'Fees collected',value:'KSh 8.42M',change:'78% of target',icon:WalletCards,tone:'gold'},{label:'Present today',value:'94.8%',change:'+2.7% vs last term',icon:ClipboardCheck,tone:'green'}];
const activities=[['AM','Amani Wanjiku enrolled','Grade 7A · by Ruth Mwangi','8 min'],['PO','Payment received','KSh 25,000 · Baraka Otieno','24 min'],['LW','Attendance completed','Grade 7A · by Lydia Wambui','42 min'],['DM','Marks published','Grade 8 Mathematics · CAT 2','1 hr']];
export default function Dashboard(){return <div className="page-stack">
 <header className="page-head dashboard-head"><div><span className="eyebrow">Monday, 19 January · Term 1, Week 3</span><h1>Good morning, James</h1><p>Here’s how Baraka Hills Academy is doing today.</p></div><div className="head-actions"><Button variant="secondary"><CalendarDays size={17}/> Academic calendar</Button><Button><Plus size={17}/> Quick add</Button></div></header>
 <section className="stat-grid">{stats.map((s,i)=><motion.div key={s.label} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.05}}><Card className={`stat stat-${s.tone}`}><span className="stat-icon"><s.icon/></span><span className="stat-copy"><small>{s.label}</small><strong>{s.value}</strong><em>{s.change}</em></span></Card></motion.div>)}</section>
 <section className="dashboard-grid"><Card className="chart-card"><header className="card-head"><div><span className="eyebrow">Financial health</span><h2>Fee collection</h2></div><select aria-label="Chart period"><option>Last 5 months</option><option>This term</option></select></header><div className="chart-summary"><strong>KSh 8.42M</strong><Badge tone="success">+12.4%</Badge><span>of KSh 10.8M target</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="fee" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="var(--primary)" stopOpacity={.3}/><stop offset="95%" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip contentStyle={{borderRadius:14,border:'1px solid var(--border)'}} formatter={v=>[`KSh ${v}M`,'Collected']}/><Area type="monotone" dataKey="fees" stroke="var(--primary)" strokeWidth={3} fill="url(#fee)"/></AreaChart></ResponsiveContainer></div></Card>
 <Card className="attendance-card"><header className="card-head"><div><span className="eyebrow">Live today</span><h2>Attendance</h2></div><Link to="/app/attendance">View report <ArrowRight size={15}/></Link></header><div className="donut-wrap"><div className="donut"><span><strong>94.8%</strong><small>Present</small></span></div><div className="legend"><span><i className="present"/><strong>1,183</strong><small>Present</small></span><span><i className="late"/><strong>24</strong><small>Late</small></span><span><i className="absent"/><strong>41</strong><small>Absent</small></span></div></div><div className="attendance-note"><Check size={16}/><span>28 of 32 classes have submitted attendance</span></div></Card></section>
 <section className="lower-grid"><Card><header className="card-head"><div><span className="eyebrow">What’s happening</span><h2>Recent activity</h2></div><Button variant="ghost" size="sm">View all</Button></header><div className="activity-list">{activities.map(a=><div className="activity" key={a[1]}><Avatar name={a[0]}/><span><strong>{a[1]}</strong><small>{a[2]}</small></span><time>{a[3]}</time></div>)}</div></Card><Card><header className="card-head"><div><span className="eyebrow">Stay ahead</span><h2>Upcoming</h2></div><Link to="/app/activities">Full calendar <ChevronRight size={15}/></Link></header><div className="event-list"><div><time><strong>22</strong><small>JAN</small></time><span><strong>Grade 7 parent meeting</strong><small>2:30 PM · Main Hall</small></span><Badge tone="violet">Meeting</Badge></div><div><time><strong>25</strong><small>JAN</small></time><span><strong>County swimming gala</strong><small>8:00 AM · Moi Sports Centre</small></span><Badge tone="info">Sports</Badge></div><div><time><strong>29</strong><small>JAN</small></time><span><strong>Mid-term marks close</strong><small>5:00 PM · Academic office</small></span><Badge tone="warning">Academic</Badge></div></div></Card><Card className="quick-card"><header className="card-head"><div><span className="eyebrow">Shortcuts</span><h2>Quick actions</h2></div></header><div className="quick-grid"><Link to="/app/students"><span><UserPlus/></span>Add student</Link><Link to="/app/fees"><span><CreditCard/></span>Record payment</Link><Link to="/app/attendance"><span><ClipboardCheck/></span>Take attendance</Link><Link to="/app/communication"><span><Megaphone/></span>Send notice</Link></div></Card></section>
 </div>}
