import { useState } from 'react';
import { ArrowRight, BadgeCheck, BarChart3, BookOpenCheck, Check, ChevronDown, CreditCard, GraduationCap, Menu, MessageSquareText, Play, School, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { Link } from 'react-router';
import { motion } from 'motion/react';
import { Logo } from '../../components/edunest/Logo';
import { Badge, Button } from '../../components/edunest/ui';

const features=[['Student journeys','One thoughtful record from admission through graduation.',Users],['Academics that flow','Marks, analysis and polished report cards without spreadsheet chaos.',GraduationCap],['Fees & M-Pesa','Instant reconciliation, receipts and clear balances for every family.',CreditCard],['Attendance & care','Faster roll calls with timely parent communication.',BookOpenCheck],['School intelligence','Live trends that help leaders act before small issues grow.',BarChart3],['Connected community','Relevant messages for parents, staff and learners in one place.',MessageSquareText]] as const;
const prices: Array<[string,string,string,string,string[]]>=[['Starter','1,500','For growing primary schools','100 students',['Core student records','Attendance & academics','Email support']],['Standard','4,000','For established schools','500 students',['Everything in Starter','Fees & M-Pesa','SMS communication','Library & transport']],['Professional','8,000','For ambitious school groups','1,500 students',['Everything in Standard','HR, payroll & finance','Advanced analytics','Priority support']]];
export default function Marketing(){const [menu,setMenu]=useState(false),[termly,setTermly]=useState(false);return <div className="marketing">
 <header className="marketing-nav"><Logo/><nav className={menu?'open':''}><a href="#platform">Platform</a><a href="#roles">For your team</a><a href="#pricing">Pricing</a><a href="#security">Security</a><Link to="/login">Sign in</Link><Link className="nav-cta" to="/register">Start free trial <ArrowRight size={15}/></Link></nav><Button variant="ghost" className="marketing-menu" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</Button></header>
 <main><section className="hero"><div className="hero-orb one"/><div className="hero-orb two"/><motion.div className="hero-copy" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><Badge tone="violet"><Sparkles size={13}/> Built for Kenyan schools</Badge><h1>Every part of your school,<br/><em>beautifully connected.</em></h1><p>EduNest brings students, academics, fees, communication and operations into one calm workspace your whole community can trust.</p><div className="hero-actions"><Link className="button button-primary button-lg" to="/register">Start your 14-day trial <ArrowRight size={18}/></Link><a className="button button-secondary button-lg" href="/demo"><Play size={17}/> See EduNest in action</a></div><div className="hero-proof"><span><Check/> No credit card</span><span><Check/> Set up in one afternoon</span><span><Check/> Kenyan support team</span></div></motion.div>
 <motion.div className="product-stage" initial={{opacity:0,y:30,scale:.98}} animate={{opacity:1,y:0,scale:1}} transition={{delay:.15,duration:.6}}><div className="mock-window"><header><span/><span/><span/><div>app.edunest.co.ke</div></header><div className="mock-shell"><aside><img src="/brand/edunest-symbol.svg"/><i/><i/><i/><i/><i/></aside><main><div className="mock-top"><span>Good morning, James</span><i/></div><div className="mock-stats"><article><small>Students</small><strong>1,248</strong><em>+36 this term</em></article><article><small>Fees collected</small><strong>KSh 8.4M</strong><em>78% of target</em></article><article><small>Present today</small><strong>94.8%</strong><em>1,183 learners</em></article></div><div className="mock-panels"><article><span>Fee collection</span><div className="mock-chart"><i/><i/><i/><i/><i/></div></article><article><span>Today’s attendance</span><div className="mock-ring">95%</div></article></div></main></div></div><div className="float-card payment"><span><CreditCard/></span><div><small>M-Pesa received</small><strong>KSh 18,500</strong><em>Amani Wanjiku · just now</em></div><Badge tone="success">Matched</Badge></div><div className="float-card attendance"><span><BadgeCheck/></span><div><strong>Attendance complete</strong><small>Grade 7A · 39 present</small></div></div></motion.div></section>
 <section className="trusted"><span>Helping school communities across Kenya thrive</span><div><strong>BARAKA HILLS</strong><strong>LAKEVIEW ACADEMY</strong><strong>ACACIA SCHOOLS</strong><strong>ST. BAKHITA</strong><strong>GREENFIELDS</strong></div></section>
 <section className="features section" id="platform"><div className="section-intro"><span className="eyebrow">One connected platform</span><h2>Less admin. More time for what matters.</h2><p>Every EduNest module shares the same reliable information, so your team spends less time reconciling and more time supporting learners.</p></div><div className="feature-grid">{features.map(([title,desc,Icon],i)=><motion.article key={title} whileHover={{y:-4}}><span className={`feature-icon fi-${i}`}><Icon/></span><h3>{title}</h3><p>{desc}</p><a href="#demo">Explore module <ArrowRight/></a></motion.article>)}</div></section>
 <section className="mpesa-section"><div className="mpesa-copy"><Badge tone="success">Made for how Kenya pays</Badge><h2>School fees that reconcile themselves.</h2><p>Parents pay using the M-Pesa they already know. EduNest matches every payment to the right learner and invoice, updates the balance, and sends a receipt in seconds.</p><ul><li><Check/> Automatic Paybill and STK reconciliation</li><li><Check/> Instant branded receipts and parent SMS</li><li><Check/> Clear unmatched-payment review</li></ul><Link to="/register">Simplify fee collection <ArrowRight/></Link></div><div className="phone"><div className="phone-screen"><span className="phone-brand">M-PESA</span><div className="success-check"><Check/></div><h3>Payment received</h3><strong>KSh 10,000.00</strong><p>Baraka Hills Academy<br/>Amani Wanjiku · ADM-2026-0148</p><div className="balance"><span>New fee balance</span><strong>KSh 35,000</strong></div><small>Receipt sent by SMS</small></div></div></section>
 <section className="roles section" id="roles"><div className="section-intro"><span className="eyebrow">Designed around people</span><h2>A better workday for everyone.</h2></div><div className="role-grid"><article><span><School/></span><h3>School leaders</h3><p>See the whole school clearly, from enrollment and performance to collections and operations.</p></article><article><span><GraduationCap/></span><h3>Teachers</h3><p>Take attendance, enter marks and share learning without unnecessary paperwork.</p></article><article><span><Users/></span><h3>Parents</h3><p>Stay close to every child’s progress, fees, attendance and school life.</p></article><article><span><CreditCard/></span><h3>Finance teams</h3><p>Reconcile faster, follow up thoughtfully and report with confidence.</p></article></div></section>
 <section className="pricing section" id="pricing"><div className="section-intro"><span className="eyebrow">Straightforward pricing</span><h2>Built to grow with your school.</h2><p>Start with a 14-day free trial. No setup fees, no credit card.</p><div className="billing-toggle"><button className={!termly?'active':''} onClick={()=>setTermly(false)}>Monthly</button><button className={termly?'active':''} onClick={()=>setTermly(true)}>Termly <Badge tone="success">Save 10%</Badge></button></div></div><div className="price-grid">{prices.map((p,i)=><article className={i===1?'popular':''} key={p[0]}>{i===1&&<span className="popular-label">Most popular</span>}<h3>{p[0]}</h3><p>{p[2]}</p><div className="price"><small>KSh</small><strong>{termly?Math.round(Number(p[1].replace(',',''))*2.7).toLocaleString():p[1]}</strong><span>/{termly?'term':'month'}</span></div><em>Up to {p[3]}</em><Link className={`button button-${i===1?'primary':'secondary'} button-md`} to="/register">Start free trial</Link><ul>{p[4].map(x=><li key={x}><Check/>{x}</li>)}</ul></article>)}</div></section>
 <section className="faq section"><div className="section-intro"><span className="eyebrow">Frequently asked</span><h2>Good questions, clear answers.</h2></div><div className="faq-list">{[['How quickly can we get started?','Most schools configure EduNest and import their first learners in one afternoon. Our team supports larger migrations.'],['Does EduNest work with M-Pesa?','Yes. Paybill, Till and STK Push payments can reconcile automatically, with a safe review queue for unmatched transactions.'],['Can teachers see fee information?','No, not by default. Granular permissions keep financial and health information available only to authorized roles.'],['What happens when internet is unreliable?','EduNest queues attendance and marks safely on the device, then synchronizes them when connectivity returns.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown/></summary><p>{a}</p></details>)}</div></section>
 <section className="security section" id="security"><div><span className="security-icon"><ShieldCheck/></span><span className="eyebrow">Safe by design</span><h2>Your school’s data stays your school’s data.</h2><p>Tenant isolation, granular permissions, complete audit history, encrypted credentials and Kenya Data Protection Act-aligned controls are built into EduNest from day one.</p><Link to="/data-protection">Read our data protection commitment <ArrowRight/></Link></div></section>
 <section className="cta" id="demo"><div><span className="eyebrow">A calmer school day starts here</span><h2>Bring your school home to EduNest.</h2><p>Join schools replacing scattered tools with one connected, caring platform.</p><div><Link className="button button-light button-lg" to="/register">Start free trial <ArrowRight/></Link><Link className="button button-outline button-lg" to="/login">Explore the demo</Link></div></div></section></main>
 <footer className="marketing-footer"><div><Logo inverse/><p>Thoughtful school software, proudly built for Africa.</p></div><div><strong>Product</strong><a href="#platform">Platform</a><a href="#pricing">Pricing</a><Link to="/login">Sign in</Link></div><div><strong>Company</strong><a href="#demo">Request a demo</a><a href="mailto:hello@edunest.co.ke">Contact</a><a href="#security">Security</a></div><div><strong>Legal</strong><Link to="/privacy">Privacy policy</Link><Link to="/terms">Terms of service</Link><Link to="/data-protection">Data protection</Link></div><small>© 2026 EduNest Technologies Ltd. Nairobi, Kenya.</small></footer>
 </div>}
