import { useMemo, useState } from 'react';
import { useParams } from 'react-router';
import { ArrowDownToLine, ChevronLeft, ChevronRight, Filter, MoreHorizontal, Plus, SlidersHorizontal } from 'lucide-react';
import toast from 'react-hot-toast';
import { moduleCopy } from '../../app/data';
import { Badge, Button, Card, Input, Modal, SearchInput, Select } from '../../components/edunest/ui';

const tone=(value:string)=>value.match(/active|complete|published|reconciled|paid|approved|healthy|compliant|good|improving|arrived|discharged/i)?'success':value.match(/pending|review|low|draft|nearly|documents/i)?'warning':'info';
export default function ModulePage(){
 const {module='students'}=useParams(); const spec=moduleCopy[module]||moduleCopy.students;
 const [rows,setRows]=useState(spec.rows),[query,setQuery]=useState(''),[open,setOpen]=useState(false);
 const filtered=useMemo(()=>rows.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const add=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget); const first=String(fd.get('name')||'New record');setRows(v=>[[first,'Auto-generated','Baraka Hills','Today','Active'],...v]);setOpen(false);toast.success(`${spec.title} record saved`)};
 const exportCsv=()=>{const csv=[spec.columns,...filtered].map(r=>r.map(c=>`"${c}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${module}.csv`;a.click();toast.success('CSV export ready')};
 return <div className="page-stack"><header className="page-head"><div><span className="eyebrow">School operations</span><h1>{spec.title}</h1><p>{spec.desc}</p></div><div className="head-actions"><Button variant="secondary" onClick={exportCsv}><ArrowDownToLine size={17}/> Export</Button><Button onClick={()=>setOpen(true)}><Plus size={17}/>{spec.action}</Button></div></header>
 <section className="module-metric"><span><small>{spec.metric}</small><strong>{spec.value}</strong></span><div><span className="pulse"/> Updated just now</div></section>
 <Card className="data-card"><div className="data-tools"><SearchInput placeholder={`Search ${spec.title.toLowerCase()}…`} value={query} onChange={e=>setQuery(e.target.value)}/><div><Button variant="secondary"><Filter size={16}/> Filter</Button><Button variant="secondary"><SlidersHorizontal size={16}/> Columns</Button></div></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all"/></th>{spec.columns.map(c=><th key={c}>{c}</th>)}<th/></tr></thead><tbody>{filtered.map((row,i)=><tr key={`${row[0]}-${i}`}><td><input type="checkbox" aria-label={`Select ${row[0]}`}/></td>{row.map((cell,j)=><td key={j}>{j===0?<strong>{cell}</strong>:j===row.length-1?<Badge tone={tone(cell)}>{cell}</Badge>:cell}</td>)}<td><Button variant="ghost" size="sm" aria-label="More actions"><MoreHorizontal/></Button></td></tr>)}</tbody></table></div><div className="mobile-records">{filtered.map((row,i)=><article key={`${row[0]}-${i}`}><header><strong>{row[0]}</strong><Badge tone={tone(row.at(-1)||'')}>{row.at(-1)}</Badge></header>{row.slice(1,-1).map((cell,j)=><p key={j}><span>{spec.columns[j+1]}</span><strong>{cell}</strong></p>)}</article>)}</div><footer className="pagination"><span>Showing {filtered.length} of {rows.length} records</span><div><Button variant="secondary" size="sm"><ChevronLeft/></Button><Button size="sm">1</Button><Button variant="secondary" size="sm"><ChevronRight/></Button></div></footer></Card>
 <Modal open={open} title={spec.action} onClose={()=>setOpen(false)}><form className="modal-form" onSubmit={add}><Input label="Name or title" name="name" required autoFocus placeholder={`Enter ${spec.title.toLowerCase()} details`}/><div className="form-row"><Select label="Status" name="status"><option>Active</option><option>Pending</option></Select><Input label="Effective date" type="date" name="date" defaultValue="2026-01-19"/></div><Input label="Notes" name="notes" placeholder="Add context for your team"/><footer><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">Save record</Button></footer></form></Modal>
 </div>}
