import { Users, GraduationCap, WalletCards, ClipboardCheck, BookOpen, Bus, HeartPulse, Library, BedDouble, Utensils, Boxes, Trophy, BriefcaseBusiness, Landmark, ChartNoAxesCombined, MessagesSquare, ShieldCheck, UserPlus, School, CalendarDays, Settings, LayoutDashboard } from 'lucide-react';

export const navGroups = [
 { label:'Workspace', items:[{slug:'dashboard',label:'Overview',icon:LayoutDashboard},{slug:'students',label:'Students',icon:Users},{slug:'staff',label:'Staff & HR',icon:BriefcaseBusiness},{slug:'classes',label:'Classes & timetable',icon:School}]},
 { label:'Learning', items:[{slug:'attendance',label:'Attendance',icon:ClipboardCheck},{slug:'academics',label:'Academics',icon:GraduationCap},{slug:'admissions',label:'Admissions',icon:UserPlus},{slug:'activities',label:'Activities',icon:Trophy}]},
 { label:'Operations', items:[{slug:'fees',label:'Fees & payments',icon:WalletCards},{slug:'communication',label:'Communication',icon:MessagesSquare},{slug:'library',label:'Library',icon:Library},{slug:'transport',label:'Transport',icon:Bus},{slug:'boarding',label:'Boarding',icon:BedDouble},{slug:'meals',label:'Meals',icon:Utensils},{slug:'inventory',label:'Inventory',icon:Boxes},{slug:'health',label:'Health',icon:HeartPulse}]},
 { label:'Intelligence', items:[{slug:'finance',label:'Finance',icon:Landmark},{slug:'analytics',label:'Analytics',icon:ChartNoAxesCombined},{slug:'settings',label:'Security & settings',icon:Settings}]},
];
export const moduleCopy: Record<string,{title:string;desc:string;metric:string;value:string;action:string;columns:string[];rows:string[][]}> = {
 students:{title:'Students',desc:'A complete, caring view of every learner.',metric:'Active learners',value:'1,248',action:'Add student',columns:['Student','Admission no.','Class','Guardian','Status'],rows:[['Amani Wanjiku','ADM-2026-0148','Grade 7A','Grace Wanjiku','Active'],['Baraka Otieno','ADM-2026-0147','Grade 8B','John Odhiambo','Active'],['Imani Kiptoo','ADM-2026-0146','Grade 6A','Rose Chebet','Active'],['Taji Mwangi','ADM-2026-0145','Grade 9A','Mary Njeri','Pending']]},
 staff:{title:'Staff & HR',desc:'People, workload, leave and payroll in one place.',metric:'Active staff',value:'84',action:'Add staff member',columns:['Staff member','Employee no.','Department','Role','Status'],rows:[['Lydia Wambui','EMP-0018','Sciences','Teacher','Active'],['Peter Omondi','EMP-0021','Finance','Accountant','Active'],['Faith Naliaka','EMP-0032','Student care','Nurse','On leave']]},
 classes:{title:'Classes & timetable',desc:'Build teaching groups and conflict-free timetables.',metric:'Teaching groups',value:'32',action:'Create class',columns:['Class','Class teacher','Learners','Room','Next lesson'],rows:[['Grade 7A','Lydia Wambui','41','Block B · 04','Mathematics · 10:20'],['Grade 7B','David Maina','39','Block B · 05','Kiswahili · 10:20'],['Grade 8A','Mercy Achieng','42','Block C · 02','Integrated Science · 11:40']]},
 attendance:{title:'Attendance',desc:'Fast roll calls, timely follow-up, better presence.',metric:'Present today',value:'94.8%',action:'Take attendance',columns:['Class','Present','Absent','Late','Completion'],rows:[['Grade 7A','39','1','1','Complete'],['Grade 7B','36','2','1','Complete'],['Grade 8A','39','3','0','Complete'],['Grade 8B','—','—','—','Pending']]},
 academics:{title:'Academics',desc:'Assessments, marks, analysis and beautiful report cards.',metric:'Marks completion',value:'87%',action:'Create assessment',columns:['Assessment','Classes','Term','Progress','Status'],rows:[['Mid-term assessment','12','Term 1','87%','Open'],['CAT 2','8','Term 1','100%','Published'],['Opening assessment','12','Term 1','100%','Published']]},
 fees:{title:'Fees & payments',desc:'From fee structure to reconciliation and parent receipts.',metric:'Collected this term',value:'KSh 8.42M',action:'Record payment',columns:['Reference','Student','Method','Amount','Status'],rows:[['QK82HDA91','Amani Wanjiku','M-Pesa','KSh 18,500','Reconciled'],['RCPT-10482','Baraka Otieno','Bank','KSh 25,000','Reconciled'],['QK75PSA44','Imani Kiptoo','M-Pesa','KSh 12,000','Reconciled'],['QK62XMP20','Unmatched','M-Pesa','KSh 8,500','Needs review']]},
 admissions:{title:'Admissions',desc:'A welcoming path from application to enrollment.',metric:'Open applications',value:'38',action:'New application',columns:['Applicant','Applying for','Guardian','Interview','Status'],rows:[['Malaika Kamau','Grade 5','Susan Kamau','18 Jan · 09:00','Interview'],['Jabali Oduor','Grade 7','Alice Oduor','20 Jan · 11:30','Documents'],['Zuri Hassan','Grade 4','Ahmed Hassan','Complete','Approved']]},
 library:{title:'Library',desc:'Catalogue, circulation and a culture of reading.',metric:'Books in circulation',value:'428',action:'Add book',columns:['Title','Author','ISBN','Available','Status'],rows:[['The River and the Source','Margaret Ogola','978-9966-46-588-3','4 of 8','Available'],['Blossoms of the Savannah','H. R. Ole Kulet','978-9966-25-336-7','0 of 6','All borrowed'],['KLB Mathematics Grade 7','KLB','978-9966-56-214-8','31 of 45','Available']]},
 transport:{title:'Transport',desc:'Safe routes, accountable fleets and informed families.',metric:'Learners transported',value:'386',action:'Add route',columns:['Route','Vehicle','Driver','Learners','Status'],rows:[['Rongai · Route 01','KDA 214P','Joseph Kariuki','48','On route'],['Kiserian · Route 02','KDB 782L','Amos Kiprotich','42','On route'],['Ngong · Route 03','KDC 119X','Dennis Ouma','39','Arrived']]},
 boarding:{title:'Boarding',desc:'Thoughtful dormitory, bed and exeat management.',metric:'Bed occupancy',value:'91%',action:'Allocate bed',columns:['Dormitory','House parent','Capacity','Occupied','Status'],rows:[['Acacia House','Anne Muthoni','120','114','Open'],['Baraka House','Samuel Otieno','96','91','Open'],['Tausi House','Jane Chebet','80','78','Nearly full']]},
 meals:{title:'Meals',desc:'Plan nutritious menus and track meal participation.',metric:'Meals served today',value:'2,316',action:'Plan menu',columns:['Day','Breakfast','Lunch','Supper','Status'],rows:[['Monday','Uji & egg','Rice, beans & fruit','Ugali & beef stew','Published'],['Tuesday','Tea & mandazi','Githeri & avocado','Rice & green grams','Published'],['Wednesday','Millet porridge','Ugali & sukuma','Chapati & beans','Draft']]},
 inventory:{title:'Inventory',desc:'Know what the school owns and where it is.',metric:'Asset value',value:'KSh 24.8M',action:'Add item',columns:['Item','Category','Location','Quantity','Status'],rows:[['Chromebook 14”','ICT equipment','Computer Lab 2','38','Good'],['A4 printing paper','Stationery','Main store','12 reams','Low stock'],['Football · Size 5','Sports','Games store','18','Good']]},
 health:{title:'Health & wellbeing',desc:'Private, permissioned care records for every learner.',metric:'Sick bay today',value:'3',action:'Record visit',columns:['Student','Class','Concern','Seen by','Status'],rows:[['Imani Kiptoo','Grade 6A','Mild headache','Faith Naliaka','Resting'],['Taji Mwangi','Grade 9A','Sports strain','Faith Naliaka','Parent notified'],['Baraka Otieno','Grade 8B','Medication','Faith Naliaka','Discharged']]},
 activities:{title:'Activities',desc:'Clubs, sports, events and every learner’s talents.',metric:'Active clubs',value:'18',action:'Create activity',columns:['Activity','Patron','Participants','Next event','Status'],rows:[['Robotics Club','David Maina','28','Regional showcase','Active'],['Girls’ Football','Mercy Achieng','24','County qualifiers','Active'],['Debate Society','Peter Mwangi','32','Inter-school debate','Active']]},
 communication:{title:'Communication centre',desc:'Clear, timely messages across every channel.',metric:'Messages this month',value:'12,840',action:'Compose message',columns:['Campaign','Audience','Channel','Delivered','Status'],rows:[['Term opening reminder','All parents','SMS','1,106 of 1,112','Complete'],['Grade 7 trip','Grade 7 parents','Email + SMS','81 of 82','Complete'],['Fee balance reminder','Selected parents','SMS','—','Scheduled']]},
 finance:{title:'Finance',desc:'A dependable view of income, spend and budgets.',metric:'Operating surplus',value:'KSh 1.82M',action:'Record expense',columns:['Transaction','Category','Date','Amount','Status'],rows:[['Textbook supplier','Learning resources','12 Jan 2026','KSh 284,000','Paid'],['Electricity · December','Utilities','10 Jan 2026','KSh 96,400','Paid'],['Laboratory supplies','Academic','08 Jan 2026','KSh 142,800','Approved']]},
 analytics:{title:'Analytics',desc:'Turn school activity into confident decisions.',metric:'Enrollment growth',value:'+8.4%',action:'Export report',columns:['Insight','Current','Previous','Change','Signal'],rows:[['Fee collection rate','78.2%','69.4%','+8.8%','Improving'],['Average attendance','94.8%','92.1%','+2.7%','Improving'],['Mean score','68.4','66.9','+1.5','Improving']]},
 settings:{title:'Security & settings',desc:'Control access, academics, branding and data policy.',metric:'Security score',value:'92%',action:'Invite administrator',columns:['Area','Summary','Updated by','Updated','Status'],rows:[['Roles & permissions','12 roles · 86 permissions','James Kariuki','Today','Healthy'],['Academic setup','2026 · Term 1','Mary Njeri','2 days ago','Active'],['Data retention','7-year policy','James Kariuki','14 days ago','Compliant']]},
};
export const chartData=[{m:'Sep',fees:4.8,attendance:91},{m:'Oct',fees:5.4,attendance:93},{m:'Nov',fees:6.1,attendance:92},{m:'Dec',fees:4.9,attendance:94},{m:'Jan',fees:8.4,attendance:95}];
export { BookOpen, CalendarDays, ShieldCheck };
